import { Component, OnInit } from '@angular/core';
import { AuctionService } from 'src/app/services/auction.service';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit {
  auctions = [
    {
        "uuid": "72e93ae5-36fd-4032-9127-76b51442cc4c",
        "state": 2,
        "endingTime": "2022-02-22T09:04:00.000Z",
        "remainingTimeInSeconds": 45067,
        "remainingTimeForInstantPurchaseInSeconds": null,
        "instantPurchasePossibleUntil": null,
        "_fk_uuid_highestBiddingBuyerUser": null,
        "currentHighestBidValue": 52,
        "currentHighestBidValueNet": 52,
        "minimumRequiredAsk": 11248,
        "minimumRequiredAskNet": 11248,
        "numBids": 0,
        "amIHighestBidder": false,
        "biddingAgentValue": null,
        "isMinAskReached": false,
        "isCrossBorderNetSale": false,
        "buyerPurchaseFee": 79,
        "buyerSuccessFee": 99,
        "buyerCrossBorderNetSaleHandlingFee": 0,
        "additionalTaxValue": null,
        "additionalTaxType": 0
    },
    {
        "uuid": "ac56c219-ae29-44bd-8230-e70ef0c7bb6d",
        "state": 2,
        "endingTime": "2022-02-22T09:12:00.000Z",
        "remainingTimeInSeconds": 45547,
        "remainingTimeForInstantPurchaseInSeconds": null,
        "instantPurchasePossibleUntil": null,
        "_fk_uuid_highestBiddingBuyerUser": null,
        "currentHighestBidValue": 1296,
        "currentHighestBidValueNet": 1296,
        "minimumRequiredAsk": 15007,
        "minimumRequiredAskNet": 15007,
        "numBids": 0,
        "amIHighestBidder": false,
        "biddingAgentValue": null,
        "isMinAskReached": false,
        "isCrossBorderNetSale": false,
        "buyerPurchaseFee": 119,
        "buyerSuccessFee": 99,
        "buyerCrossBorderNetSaleHandlingFee": 0,
        "additionalTaxValue": null,
        "additionalTaxType": 0
    },
    {
        "uuid": "009aed04-f824-491f-abfe-8a43cb87446f",
        "state": 2,
        "endingTime": "2022-02-22T09:08:00.000Z",
        "remainingTimeInSeconds": 45307,
        "remainingTimeForInstantPurchaseInSeconds": null,
        "instantPurchasePossibleUntil": null,
        "_fk_uuid_highestBiddingBuyerUser": null,
        "currentHighestBidValue": 1448,
        "currentHighestBidValueNet": 1448,
        "minimumRequiredAsk": 14184,
        "minimumRequiredAskNet": 14184,
        "numBids": 0,
        "amIHighestBidder": false,
        "biddingAgentValue": null,
        "isMinAskReached": false,
        "isCrossBorderNetSale": false,
        "buyerPurchaseFee": 129,
        "buyerSuccessFee": 99,
        "buyerCrossBorderNetSaleHandlingFee": 0,
        "additionalTaxValue": null,
        "additionalTaxType": 0
    },
    {
        "uuid": "1abea867-4d38-407d-ae64-c016a4aff0d7",
        "state": 2,
        "endingTime": "2022-02-22T09:10:00.000Z",
        "remainingTimeInSeconds": 45427,
        "remainingTimeForInstantPurchaseInSeconds": null,
        "instantPurchasePossibleUntil": null,
        "_fk_uuid_highestBiddingBuyerUser": null,
        "currentHighestBidValue": 1302,
        "currentHighestBidValueNet": 1094.1176470588,
        "minimumRequiredAsk": 14469,
        "minimumRequiredAskNet": 12158.8235294118,
        "numBids": 0,
        "amIHighestBidder": false,
        "biddingAgentValue": null,
        "isMinAskReached": false,
        "isCrossBorderNetSale": false,
        "buyerPurchaseFee": 119,
        "buyerSuccessFee": 99,
        "buyerCrossBorderNetSaleHandlingFee": 0,
        "additionalTaxValue": null,
        "additionalTaxType": 0
    },
    {
        "uuid": "b4a99960-431a-4794-941e-bf40c8c4417e",
        "state": 2,
        "endingTime": "2022-02-22T09:14:00.000Z",
        "remainingTimeInSeconds": 45667,
        "remainingTimeForInstantPurchaseInSeconds": null,
        "instantPurchasePossibleUntil": null,
        "_fk_uuid_highestBiddingBuyerUser": null,
        "currentHighestBidValue": 1472,
        "currentHighestBidValueNet": 1472,
        "minimumRequiredAsk": 21057,
        "minimumRequiredAskNet": 21057,
        "numBids": 0,
        "amIHighestBidder": false,
        "biddingAgentValue": null,
        "isMinAskReached": false,
        "isCrossBorderNetSale": false,
        "buyerPurchaseFee": 129,
        "buyerSuccessFee": 99,
        "buyerCrossBorderNetSaleHandlingFee": 0,
        "additionalTaxValue": null,
        "additionalTaxType": 0
    },
    {
        "uuid": "3291a2e3-87e1-41be-ae6a-592125aad7ee",
        "state": 2,
        "endingTime": "2022-02-22T09:00:00.000Z",
        "remainingTimeInSeconds": 44827,
        "remainingTimeForInstantPurchaseInSeconds": null,
        "instantPurchasePossibleUntil": null,
        "_fk_uuid_highestBiddingBuyerUser": null,
        "currentHighestBidValue": 62,
        "currentHighestBidValueNet": 62,
        "minimumRequiredAsk": 1123,
        "minimumRequiredAskNet": 1123,
        "numBids": 0,
        "amIHighestBidder": false,
        "biddingAgentValue": null,
        "isMinAskReached": false,
        "isCrossBorderNetSale": false,
        "buyerPurchaseFee": 79,
        "buyerSuccessFee": 99,
        "buyerCrossBorderNetSaleHandlingFee": 0,
        "additionalTaxValue": null,
        "additionalTaxType": 0
    },
    {
        "uuid": "cbac8917-dfba-458a-9c9f-8a76fdfc1c6e",
        "state": 2,
        "endingTime": "2022-02-22T09:06:00.000Z",
        "remainingTimeInSeconds": 45187,
        "remainingTimeForInstantPurchaseInSeconds": null,
        "instantPurchasePossibleUntil": null,
        "_fk_uuid_highestBiddingBuyerUser": null,
        "currentHighestBidValue": 374,
        "currentHighestBidValueNet": 314.2857142857,
        "minimumRequiredAsk": 20464,
        "minimumRequiredAskNet": 17196.6386554622,
        "numBids": 0,
        "amIHighestBidder": false,
        "biddingAgentValue": null,
        "isMinAskReached": false,
        "isCrossBorderNetSale": false,
        "buyerPurchaseFee": 79,
        "buyerSuccessFee": 99,
        "buyerCrossBorderNetSaleHandlingFee": 0,
        "additionalTaxValue": null,
        "additionalTaxType": 0
    },
    {
        "uuid": "8bdc4def-d582-49b7-a228-107ac48189b3",
        "state": 2,
        "endingTime": "2022-02-22T09:02:00.000Z",
        "remainingTimeInSeconds": 44947,
        "remainingTimeForInstantPurchaseInSeconds": null,
        "instantPurchasePossibleUntil": null,
        "_fk_uuid_highestBiddingBuyerUser": "ce5e3d7f-3a3d-4fde-96bc-986d5f483df8",
        "currentHighestBidValue": 7500,
        "currentHighestBidValueNet": 7500,
        "minimumRequiredAsk": null,
        "minimumRequiredAskNet": 6515,
        "numBids": 2,
        "amIHighestBidder": false,
        "biddingAgentValue": null,
        "isMinAskReached": true,
        "isCrossBorderNetSale": false,
        "buyerPurchaseFee": 269,
        "buyerSuccessFee": 99,
        "buyerCrossBorderNetSaleHandlingFee": 0,
        "additionalTaxValue": null,
        "additionalTaxType": 0
    }
];
  constructor(private userService: UserService, private auction: AuctionService) {}

  ngOnInit(){
    this.auction.getAllAuctionForSalesMan().subscribe(response => {

      console.log(response, new Date().toLocaleString());
    })
  }

}
